import { 
	TASK_ACTIVE, 
	TASK_COMPLETE, 
	TASK_DEFAULT, 
	TASK_QUEUED,
	TASK_THREAD_ACTIVE,
	TASK_THREAD_COMPLETE,
	TASK_THREAD_DEFAULT,
	TASK_THREAD_QUEUED,
} from './constants';
import {
	TASK_ACTIVE_STRING,
	TASK_COMPLETE_STRING,
	TASK_DEFAULT_STRING,
	TASK_QUEUED_STRING,
	TASK_THREAD_ACTIVE_STRING,
	TASK_THREAD_COMPLETE_STRING,
	TASK_THREAD_DEFAULT_STRING,
	TASK_THREAD_QUEUED_STRING
} from './objectStatusStrings';

export const taskStatusMap = {
	[TASK_ACTIVE]: TASK_ACTIVE_STRING,
	[TASK_COMPLETE]: TASK_COMPLETE_STRING,
	[TASK_DEFAULT]: TASK_DEFAULT_STRING,
	[TASK_QUEUED]: TASK_QUEUED_STRING,
}

export const taskThreadStatusMap = {
	[TASK_THREAD_ACTIVE]: TASK_THREAD_ACTIVE_STRING,
	[TASK_THREAD_COMPLETE]: TASK_THREAD_COMPLETE_STRING,
	[TASK_THREAD_DEFAULT]: TASK_THREAD_DEFAULT_STRING,
	[TASK_THREAD_QUEUED]: TASK_THREAD_QUEUED_STRING,
}